version: '3'
services:
  pgdb:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB     
    ports:
      - "5432:5432"
  admin:
    image: adminer
    ports:
      - "8080:8080"
